name: small_refresh
description: This is a refresh view based on CustomScrollView with Smooth animations,and you can customize your header view or footer view simply.
version: 1.0.18
repository: https://github.com/flappygod/small_refresh.git

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0
  synchronized: ^3.1.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
